### ISSUE TITLE
Enhance Carousel, flex in homepage

### ISSUE THREAD

**Issue by Sriver27** [anups1ngh/Tasty-treats#3]

**Comment by anups1ngh** [comment]
i think now it has been fixed. @Sriver27

**Comment by Sriver27** [comment]
![Screenshot 2023-11-24 115118](https://github.com/anups1ngh/Tasty-treats/assets/75061992/72c401c4-7d53-4b4c-b717-472604238b94)
Homepage flex still not solved. Need to update css .

**Comment by anups1ngh** [comment]
actually the size of restaurant card is big so it can't fit in your screen width
